routes/web.php
<?php

// use App\Http\Controllers\IndoregionController
use App\Http\Controllers\Mahasiswa\mahasiswaController;
use App\Kampus;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|   // $kampus = Kampus::paginate(8);
*/

Route::get('/', 'frontController@index')->name('kampusku');
Route::get('profilkampus/{id}', 'frontController@profilkampus')->name('profilkampus');
Route::get('/DaftarSemuaKampus', 'frontController@allkampus')->name('all-kampus');

// Auth::routes(['verify' => true]);
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/siakad', 'HomeController@mhs')->name('mhs');
// dosen
Route::get('/dosen', 'Admin\ProfildosenController@index')->name('dosen');


Route::get('/pmb', 'HomeController@pmb')->name('pmb');
Route::get('/daftarpmb/{id}', 'HomeController@daftarpmb')->name('daftarpmb');
Route::post('/daftarpmb/daftarpmbstore', 'HomeController@daftarpmbstore')->name('daftarpmbstore');
Route::post('/getkabupaten', 'HomeController@getkabupaten')->name('getkabupaten');
Route::post('/getkecamatan', 'HomeController@getkecamatan')->name('getkecamatan');
Route::post('/getdesa', 'HomeController@getdesa')->name('getdesa');

//Camaba
Route::group(['middleware' => ['auth', 'CekRole:camaba']], function () {
    Route::get('formpendaftaran', 'Pmb\pmbController@create')->name('form.daftar');
    Route::post('pendaftaran', 'Pmb\pmbController@store')->name('simpan.daftar');
});

Route::group(['middleware' => ['auth', 'CekRole:admin'], 'prefix' => 'Admin_Kemahasiswaan'], function () {
    Route::namespace('Admin')->group(function () {
        Route::resource('kampus', 'kampusController')->parameters(['kampus' => 'kampus',]);
        Route::resource('prodi', 'prodiController');
        Route::resource('fakultas', 'FakultasController');
        // Route::resource('dataprodikampus', 'prodikampusController');
        Route::resource('infopmb', 'infopmbController');
        Route::resource('pendaftar', 'CamabaController');
        Route::resource('student', 'StudentController');
        Route::resource('dosen', 'DosenController');
        Route::get('diterima/{id}/{key}', 'CamabaController@diterima')->name('diterima');
    });
});

Route::group(['middleware' => ['auth', 'CekRole:mahasiswa'], 'prefix' => 'Mahasiswa'], function () {
    Route::namespace('Mahasiswa')->group(function () {

        /* Route::get('/siswa','SiswaController@index');
        Route::post('/siswa/create','SiswaController@create');
        Route::get('/siswa/{siswa}/edit','SiswaController@edit');
        Route::post('/siswa/{siswa}/update','SiswaController@update');
        Route::get('/siswa/{siswa}/delete','SiswaController@delete');
        Route::get('/siswa/{siswa}/profile','SiswaController@profile');
        Route::post('/siswa/{siswa}/addnilai','SiswaController@addnilai'); */

        // Route::get('/mahasiswa/{mahasiswa}/edit','mahasiswaController@edit');

        // Route::get('/mahasiswa/{mahasiswa}/edit', 'mahasiswaController@edit');
        Route::resource('mahasiswa', 'mahasiswaController');
        // Route::resource('mahasiswa', 'mahasiswaController')->parameters(['mahasiswa' => 'mahasiswa',]);
        Route::get('krs', 'mahasiswaController@krs')->name('krs');
        Route::get('khs', 'mahasiswaController@khs')->name('khs');
        Route::get('transkrip', 'mahasiswaController@nilai')->name('nilai');
        Route::get('Elearning', 'mahasiswaController@learning')->name('learning');
        Route::get('materi', 'mahasiswaController@materi')->name('materi');
    });
});

Route::group(['middleware' => ['auth', 'verified', 'CekRole:pmb'], 'prefix' => 'Pmb'], function () {
    Route::namespace('Pmb')->group(function () {
        Route::resource('pmb', 'pmbController')->parameters(['pmb' => 'pmb',]);
        Route::get('pendaftaran', 'pmbController@pendaftaran')->name('pendaftaran');
    });
});

Route::group(['middleware' => ['auth', 'CekRole:adminakademik'], 'prefix' => 'Adminakademik'], function () {
    Route::namespace('Admin')->group(function () {
        Route::resource('datatahunakademik', 'DatathnakademikController')->parameters(['datatahunakademik' => 'datatahunakademik',]);
        Route::resource('datasemester', 'DatasemesterController');
        Route::resource('datamatakuliah', 'DatamatakuliahController');
        Route::resource('jadwalkuliah', 'JadwalkuliahController');
        Route::resource('datakrs', 'DatakrsController');
        Route::resource('datakhs', 'DatakhsController');
        Route::resource('datatranskipnilai', 'DatatranskipnilaiController');
    });
});

Route::group(['middleware' => ['auth', 'CekRole:admindosen'], 'prefix' => 'Admindosen'], function () {
    Route::namespace('Admin')->group(function () {
        Route::resource('profildosen', 'ProfildosenController')->parameters(['profildosen' => 'profildosen',]);
        Route::resource('jadwaldosen', 'JadwalkuliahdosenController');
        Route::resource('absensi', 'AbsensiController');
        Route::resource('modulmateri', 'ModulmateriController');
        Route::get('/detailmateri/{id}/materi', 'ModulmateriController@materi')->name('detailmateri');
    });
});

app/Profildosen.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Profildosen extends Model
{
    //
}

app/Http/Controllers/Admin/ProfildosenController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Dosen;
use App\User;

class ProfildosenController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
        $dosen = Dosen::where('user_id', auth()->user()->id)->first();
        // dd($dosen);
        $value = User::where('id', $dosen->user_id)->first();
        //dd($value, $dosen);

        return view('AdminDosen.Profildosen.index', compact('dosen', 'value'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('AdminDosen.Profildosen.edit');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(/* $id */)
    {
        //
        return view('AdminDosen.Profildosen.edit');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/AdminDosen/Profildosen/edit.blade.php
@extends('layouts.cork')

@section('content')
<div id="flStackForm" class="col-lg-12 layout-spacing layout-top-spacing">
    <div class="statbox widget box box-shadow col-md-12">
        <div class="widget-header">                                
            <div class="row">
                <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                    <h4>UPDATE DATA DOSEN </h4>
                </div>                                                                        
            </div>
        </div>
        <div class="widget-content widget-content-area">
            <form action="" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label>Pilih Kampus</label>
                    <select class="form-control  basic" name="kampus_id">
                        <option value=""> --- Pilih kampus --- </option>
                       
                    </select>
                </div>
                <div class="form-group">
                    <label>Pilih Prodik</label>
                    <select class="form-control  basic" name="prodi_id">
                        <option value=""> --- Pilih Prodi --- </option>
                       
                    </select>
                </div>
                <div class="form-group">
                    <label>Pilih Fakultas</label>
                    <select class="form-control  basic" name="fakultas_id">
                        <option value=""> --- Pilih Fakultas --- </option>
                       
                    </select>
                </div>
                <div class="form-group">
                    <label>Nama Dosen</label>
                    <input type="text" name="nama_dosen" class="form-control" placeholder="Masukkan Nama "
                        value="{{ old('nama_dosen') }}">
                </div>
                <div class="form-group">
                    <label>NIP</label>
                    <input type="number" name="nip" class="form-control" placeholder="Masukkan Nip "
                        value="{{ old('nip') }}">
                </div>
                <div class="form-group">
                    <label>Jenis Kelamin Dosen</label>
                    <select class="form-control" name="jenis_kelamin" id="">
                        <option value="L"{{--  @if($mahasiswa->jenis_kelamin == 'L') selected @endif --}} >LAKI-LAKI</option>
                        <option value="P" {{-- @if($mahasiswa->jenis_kelamin == 'P') selected @endif --}} >PEREMPUAN</option>
                    </select>
                </div>
                <div class="form-group">
                    <label>Pendidikan Terakhir</label>
                    <select class="form-control" name="pendidikan_ayah" id="">
                        <option value="SMU" {{-- @if($mahasiswa->pendidikan_ayah == 'SMU') selected @endif --}} >SMU</option>
                        <option value="S1" {{-- @if($mahasiswa->pendidikan_ayah == 'S1') selected @endif --}} >S1</option>
                        <option value="S2" {{-- @if($mahasiswa->pendidikan_ayah == 'S2') selected @endif --}} >S2</option>
                        <option value="S3" {{-- @if($mahasiswa->pendidikan_ayah == 'S3') selected @endif --}} >S3</option>
                    </select>
                </div> 
                <div class="form-group">
                    <label>Email Dosen</label>
                    <input type="email" name="email" class="form-control" placeholder="Masukkan Email "
                        value="{{ old('email') }}">
                </div>
                <div class="form-group">
                    <label>No Telpon</label>
                    <input type="text" name="no_telpon" class="form-control" placeholder="Masukkan No Telpon"
                        value="{{ old('no_telpon') }}">
                </div>
                <div class="form-group mb-4 mt-3">
                    <label for="exampleFormControlFile1">Foto Dosen</label>
                    <input type="file" name="foto_dosen" class="form-control-file" id="exampleFormControlFile1">
                </div>
                <div class="form-group-inner">
                    <label>Alamat Dosen</label>
                    <textarea name="alamat" id="alamat"
                        class="form-control"> {{-- {{ old('alamat', $mahasiswa->alama) }} --}} </textarea>
                </div>
                <button type="submit" class="btn btn-primary mt-3">UPDATE DOSEN</button>
            </form>

           
        </div>
    </div>
</div>
@endsection

resources/views/AdminDosen/Profildosen/index.blade.php
@extends('layouts.cork')

@section('content')
    <div id="tableHover" class="col-lg-12 col-12 layout-spacing">
        <div class="statbox widget box box-shadow">
            <div class="widget-header">
                <div class="row">
                    <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                        <h4>Profil Dosen</h4>
                        {{-- <a class="btn btn-outline-primary mt-3 mr-3" href="{{ route('absensi.create') }}">UPDATE DATA DOSEN</a> --}}
                        {{-- <a class="btn btn-outline-primary mt-3 mr-3" href="{{ route('profildosen.edit', 1) }}">UPDATE DATA DOSEN</a> --}}
               
                    </div>
                </div>
            </div>

            {{-- <div class="col-xl-2 col-md-6 col-sm-6 col-12 text-right">
                <div class="form-group mt-2">
                    <a class="btn btn-outline-primary mt-3 mr-3" href="{{ route('absensi.create') }}">PROSES</a>
                </div>
            </div> --}}
            
            <div class="widget-content widget-content-area">
                <img width="200px" src="{{ asset($dosen->foto_dosen) }}" alt="" style="margin-left: 40%">
                <h4 style="margin-top: 10px; margin-left: 40%;">{{ $value->name }}</h4>
                <p style="margin-left: 40%">NIP. {{ $dosen->nip }}</p>
                <br>
                <div class="row" style="margin-left: 20%">
                    <div class="col-xl-6 col-md-6 col-sm-6 col-12">
                        <p><strong>Pendidikan : </strong>{{ $dosen->pendidikan }}</p>
                    </div>
                    <div class="col-xl-6 col-md-6 col-sm-6 col-12">
                        @if ($dosen->jenis_kelamin == 'L')
                            <p><strong>Jenis Kelamin : </strong> Laki-Laki</p>
                        @elseif ($dosen->jenis_kelamin == 'P')
                            <p><strong>Jenis Kelamin : </strong> Perempuan</p>
                        @endif
                    </div>
                </div>
                <br>
                <div class="row" style="margin-left: 20%">
                    <div class="col-xl-6 col-md-6 col-sm-6 col-12">
                        <p><strong>No Telpon : </strong>{{ $dosen->no_telpon }}</p>
                    </div>
                    <div class="col-xl-6 col-md-6 col-sm-6 col-12">
                        <p><strong>E-mail : </strong>{{ $dosen->email }}</p>
                    </div>
                </div>
                <br>
                <div class="row" style="margin-left: 20%">
                    <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                        <p><strong>Alamat : </strong> {!! $dosen->alamat !!}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div id="tableHover" class="col-lg-12 col-12 layout-spacing">
        <div class="statbox widget box box-shadow">
            {{-- <div class="widget-header">
                <div class="row">
                    <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                        <h4>Profil Dosen</h4>
                    </div>
                </div>
            </div> --}}
            <div class="widget-content widget-content-area">
                {{-- <img width="200px" src="{{ asset('front') }}/images/testimonial-3.jpg" alt="" style="margin-left: 40%">
                <h4 style="margin-top: 10px; margin-left: 40%;">Anton Susilo</h4>
                <p style="margin-left: 40%">NIP. 112.45556.98</p>
                <br>
                <div class="row" style="margin-left: 20%">
                    <div class="col-xl-6 col-md-6 col-sm-6 col-12">
                        <p><strong>Pendidikan : </strong>Magister Teknik Informatika</p>
                    </div>
                    <div class="col-xl-6 col-md-6 col-sm-6 col-12">
                        <p><strong>Jenis Kelamin : </strong> Laki-Laki</p>
                    </div>
                </div>
                <br>
                <div class="row" style="margin-left: 20%">
                    <div class="col-xl-6 col-md-6 col-sm-6 col-12">
                        <p><strong>No Telpon : </strong>08779569807</p>
                    </div>
                    <div class="col-xl-6 col-md-6 col-sm-6 col-12">
                        <p><strong>E-mail : </strong>dosen@gmail.com</p>
                    </div>
                </div>
                <br>
                <div class="row" style="margin-left: 20%">
                    <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                        <p><strong>Alamat : </strong>Jl. Garuda</p>
                    </div>
                </div> --}}

                
            </div>
        </div>
    </div>


@endsection