routes/web.php
<?php

// use App\Http\Controllers\IndoregionController
use App\Http\Controllers\Mahasiswa\mahasiswaController;
use App\Kampus;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|   // $kampus = Kampus::paginate(8);
*/

Route::get('/', 'frontController@index')->name('kampusku');
Route::get('profilkampus/{id}', 'frontController@profilkampus')->name('profilkampus');
Route::get('/DaftarSemuaKampus', 'frontController@allkampus')->name('all-kampus');

// Auth::routes(['verify' => true]);
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/siakad', 'HomeController@mhs')->name('mhs');
// dosen
Route::get('/dosen', 'Admin\ProfildosenController@index')->name('dosen');


Route::get('/pmb', 'HomeController@pmb')->name('pmb');
Route::get('/daftarpmb/{id}', 'HomeController@daftarpmb')->name('daftarpmb');
Route::post('/daftarpmb/daftarpmbstore', 'HomeController@daftarpmbstore')->name('daftarpmbstore');
Route::post('/getkabupaten', 'HomeController@getkabupaten')->name('getkabupaten');
Route::post('/getkecamatan', 'HomeController@getkecamatan')->name('getkecamatan');
Route::post('/getdesa', 'HomeController@getdesa')->name('getdesa');

//Camaba
Route::group(['middleware' => ['auth', 'CekRole:camaba']], function () {
    Route::get('formpendaftaran', 'Pmb\pmbController@create')->name('form.daftar');
    Route::post('pendaftaran', 'Pmb\pmbController@store')->name('simpan.daftar');
});

Route::group(['middleware' => ['auth', 'CekRole:admin'], 'prefix' => 'Admin_Kemahasiswaan'], function () {
    Route::namespace('Admin')->group(function () {
        Route::resource('kampus', 'kampusController')->parameters(['kampus' => 'kampus',]);
        Route::resource('prodi', 'prodiController');
        Route::resource('fakultas', 'FakultasController');
        // Route::resource('dataprodikampus', 'prodikampusController');
        Route::resource('infopmb', 'infopmbController');
        Route::resource('pendaftar', 'CamabaController');
        Route::resource('student', 'StudentController');
        Route::resource('dosen', 'DosenController');
        Route::get('diterima/{id}/{key}', 'CamabaController@diterima')->name('diterima');
    });
});

Route::group(['middleware' => ['auth', 'CekRole:mahasiswa'], 'prefix' => 'Mahasiswa'], function () {
    Route::namespace('Mahasiswa')->group(function () {

        /* Route::get('/siswa','SiswaController@index');
        Route::post('/siswa/create','SiswaController@create');
        Route::get('/siswa/{siswa}/edit','SiswaController@edit');
        Route::post('/siswa/{siswa}/update','SiswaController@update');
        Route::get('/siswa/{siswa}/delete','SiswaController@delete');
        Route::get('/siswa/{siswa}/profile','SiswaController@profile');
        Route::post('/siswa/{siswa}/addnilai','SiswaController@addnilai'); */

        // Route::get('/mahasiswa/{mahasiswa}/edit','mahasiswaController@edit');

        // Route::get('/mahasiswa/{mahasiswa}/edit', 'mahasiswaController@edit');
        Route::resource('mahasiswa', 'mahasiswaController');
        // Route::resource('mahasiswa', 'mahasiswaController')->parameters(['mahasiswa' => 'mahasiswa',]);
        Route::get('krs', 'mahasiswaController@krs')->name('krs');
        Route::get('khs', 'mahasiswaController@khs')->name('khs');
        Route::get('transkrip', 'mahasiswaController@nilai')->name('nilai');
        Route::get('Elearning', 'mahasiswaController@learning')->name('learning');
        Route::get('materi', 'mahasiswaController@materi')->name('materi');
    });
});

Route::group(['middleware' => ['auth', 'verified', 'CekRole:pmb'], 'prefix' => 'Pmb'], function () {
    Route::namespace('Pmb')->group(function () {
        Route::resource('pmb', 'pmbController')->parameters(['pmb' => 'pmb',]);
        Route::get('pendaftaran', 'pmbController@pendaftaran')->name('pendaftaran');
    });
});

Route::group(['middleware' => ['auth', 'CekRole:adminakademik'], 'prefix' => 'Adminakademik'], function () {
    Route::namespace('Admin')->group(function () {
        Route::resource('datatahunakademik', 'DatathnakademikController')->parameters(['datatahunakademik' => 'datatahunakademik',]);
        Route::resource('datasemester', 'DatasemesterController');
        Route::resource('datamatakuliah', 'DatamatakuliahController');
        Route::resource('jadwalkuliah', 'JadwalkuliahController');
        Route::resource('datakrs', 'DatakrsController');
        Route::resource('datakhs', 'DatakhsController');
        Route::resource('datatranskipnilai', 'DatatranskipnilaiController');
    });
});

Route::group(['middleware' => ['auth', 'CekRole:admindosen'], 'prefix' => 'Admindosen'], function () {
    Route::namespace('Admin')->group(function () {
        Route::resource('profildosen', 'ProfildosenController')->parameters(['profildosen' => 'profildosen',]);
        Route::resource('jadwaldosen', 'JadwalkuliahdosenController');
        Route::resource('absensi', 'AbsensiController');
        Route::resource('modulmateri', 'ModulmateriController');
        Route::get('/detailmateri/{id}/materi', 'ModulmateriController@materi')->name('detailmateri');
    });
});

resources/views/Admin_Kemahasiswaan/Pendaftar/index.blade.php
@extends('layouts.cork')

@section('content')
    <div id="tableHover" class="col-lg-12 col-12 layout-spacing">
        <div class="statbox widget box box-shadow">
            <div class="widget-header">
                <div class="row">
                    <div class="col-xl-6 col-md-6 col-sm-6 col-12">
                        <h4>Info Pendaftaran PMB</h4>
                    </div>
                    <div class="col-xl-3 col-md-6 col-sm-6 col-12 text-right">
                        <div class="form-group mt-3">
                            <select class="form-control" id="">
                                <option value="">Filter Tahun Akademik</option>
                                <option value="1">2020</option>
                                <option value="2">2021</option>
                                <option value="3">2022</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-xl-3 col-md-6 col-sm-6 col-12 text-right">
                        <div class="form-group mt-3">
                            <select class="form-control" id="">
                                <option value="">Filter Kampus</option>
                                <option value="1">UTY</option>
                                <option value="2">UGM</option>
                                <option value="3">UAD</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
            <div class="widget-content widget-content-area">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover mb-4">
                        <thead>
                            <tr>
                                <th class="text-center">No</th>
                                <th class="text-center">Nama Kampus</th>
                                <th class="text-center">Prodi</th>
                                <th class="text-center">Nama Calon Mahasiswa</th>
                                <th class="text-center">Asal Sekolah</th>
                                <th class="text-center">Status Pendaftar</th>
                                <th class="text-center">Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($data as $item => $camaba)
                                @php
                                    $user = App\User::where('id', $camaba->user_id)->first();
                                @endphp
                                <tr>
                                    <td class="text-center"> {{ $data->firstItem() + $item }} </td>
                                    {{-- <td class="text-center"> {{ $camaba->kampus_id }}</td> --}}
                                    <td class="text-center"> {{ $camaba->kampus['nama_kampus'] }}</td>
                                    <td class="text-center"> {{ $camaba->prodi['nama_prodi'] }}</td>
                                    <td class="text-center"> {{ $camaba->nama_camaba }}</td>
                                    <td class="text-center"> {{ $camaba->asal_sekolah }}</td>
                                    <td class="text-center"><a class="btn btn-warning"> {{ $user->role }} </a></td>
                                    <td class="text-center">
                                        <a href="{{ route('pendaftar.show', $camaba->id) }}">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                                viewBox="0 0 24 24" fill="none" stroke="#000000" stroke-width="2"
                                                stroke-linecap="round" stroke-linejoin="round">
                                                <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path>
                                                <circle cx="12" cy="12" r="3"></circle>
                                            </svg>
                                        </a>
                                    </td>
                                </tr>
                            @empty
                            @endforelse
                        </tbody>
                    </table>
                </div>
                {{ $data->links() }}
            </div>
        </div>
    </div>
@endsection

resources/views/Admin_Kemahasiswaan/Pendaftar/show.blade.php
@extends('layouts.cork')

@section('content')
    <div id="flStackForm" class="col-lg-12 layout-spacing layout-top-spacing">
        <div class="statbox widget box box-shadow col-md-12">
            <div class="widget-header">
                <div class="row">
                    <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                        <h4>Detail Pendaftar Camaba Oktober</h4>
                    </div>
                </div>
            </div>
            <div class="widget-content widget-content-area">
                <div class="form-group mt-5">
                    <div class="form-group mt-5">
                        <label>Nama Kampus</label>
                        <input type="text" name="kampus_id" class="form-control text-dark"
                            value="{{ $camaba->kampus['nama_kampus'] }}" readonly>
                    </div>
                </div>
                <div class="form-group">
                    <label>NIK</label>
                    <input type="text" name="nik" class="form-control text-dark" value="{{ $camaba->nik }}"
                        readonly>
                </div>
                <div class="form-group">
                    <label>Nama Camaba</label>
                    <input type="text" name="nama_camaba" class="form-control text-dark"
                        value="{{ $camaba->nama_camaba }}" readonly>
                </div>
                <div class="form-group">
                    <label>Tempat Lahir, Tanggal Lahir</label>
                    <input type="text" name="tempat_lahir" class="form-control text-dark"
                        value="{{ $camaba->tempat_lahir }}, {{ Carbon\Carbon::parse($camaba->tanggal_lahir)->translatedFormat('d F Y') }}"
                        readonly>
                </div>
                <div class="form-group">
                    <label>Jenis Kelamin</label>
                    <input type="text" name="jenis_kelamin" class="form-control text-dark"
                        value="{{ $camaba->jenis_kelamin }}" readonly>
                </div>
                <div class="form-group">
                    <label>Agama</label>
                    <input type="text" name="agama" class="form-control text-dark" value="{{ $camaba->agama }}"
                        readonly>
                </div>
                <div class="form-group">
                    <label>Nomor Telpon</label>
                    <input type="text" name="no_tlp" class="form-control text-dark" value="{{ $camaba->no_tlp }}"
                        readonly>
                </div>
                <div class="form-group">
                    <label>Email</label>
                    <input type="text" name="email" class="form-control text-dark" value="{{ $camaba->email }}"
                        readonly>
                </div>
                <div class="form-group mb-4">
                    <label for="exampleFormControlTextarea1">Alamat Lengkap</label>
                    <textarea name="alamat" class="form-control text-dark" id="exampleFormControlTextarea1" rows="3" readonly>{{ $camaba->alamat }}</textarea>
                </div>
                <div class="form-group">
                    <label>Asal Sekolah</label>
                    <input type="text" name="asal_sekolah" class="form-control text-dark"
                        value="{{ $camaba->asal_sekolah }}" readonly>
                </div>
                <div class="form-group">
                    <label>Program Studi yang di pilih</label>
                    <input type="text" name="prodi_id" class="form-control text-dark"
                        value="{{ $camaba->prodi['nama_prodi'] }}" readonly>
                </div>
                <div class="form-group">
                    <label>Foto Camaba</label>
                    <td align="center">
                        <img width="100px" src="{{ asset($camaba->foto) }}" alt="">
                        {{-- <button onclick="download()" target="_new" class="btn btn-primary mt-3">Download Foto</button> --}}
                    </td>
                </div>
                <div class="row">
                    <div class="col-xl-4 col-md-6 col-sm-6 col-12">
                        <label>FILE TRANSKIP</label>
                        <td align="center">
                            <iframe src="{{ asset($camaba->file_ijazah) }}" align="top" height="400" width="100%"
                                frameborder="0" scrolling="auto"></iframe>
                        </td>
                    </div>
                    <div class="col-xl-4 col-md-6 col-sm-6 col-12">
                        <label>FILE TRANSKIP</label>
                        <td align="center">
                            <iframe src="{{ asset($camaba->file_transkrip) }}" align="top" height="400" width="100%"
                                frameborder="1" scrolling="auto1"></iframe>
                        </td>
                    </div>

                    <div class="col-xl-4 col-md-6 col-sm-6 col-12">
                        <label>FILE TRANSKIP</label>
                        <td align="center">
                            <iframe src="{{ asset($camaba->file_raport) }}" align="top" height="400" width="100%"
                                frameborder="2" scrolling="auto2"></iframe>
                        </td>
                    </div>
                </div>
                <br>
                <br>
                <br>
                <br>
                <div class="breadcome-list link-submit">
                    <span class="form-group center">
                        <b style="position: center">Verifikasi Pendaftaran Mahasiswa</b>
                    </span>
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <a href="{{ url('Admin_Kemahasiswaan/diterima/' . $camaba->user_id . '/' . $camaba->id) }}"
                                type="button" class="btn btn-danger mt-3" style="position: right">DI TERIMA</a>
                            <a href="" type="button" class="btn btn-info mt-3" style="position: right">DI
                                TOLAK</a>
                        </div>
                    </div>
                </div>
                {{-- </form> --}}
            </div>
        </div>
    </div>
@endsection
<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.26.1/axios.min.js"></script>
<script>
    function download() {
        axios({
                url: 'https://source.unsplash.com/random/500x500',
                method: 'GET',
                responseType: 'blob'
            })
            .then((response) {
                const url = window.URL.createObjectURL(new Blob([response.data]))
                const link = document.createElement('a')
                link.href = link
                link.setAttribute('download', 'foto.png')
                document.body.appendChild(link)
                link.click()
            })
    }
</script>