routes/web.php
<?php

// use App\Http\Controllers\IndoregionController
use App\Http\Controllers\Mahasiswa\mahasiswaController;
use App\Kampus;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|   // $kampus = Kampus::paginate(8);
*/

Route::get('/', 'frontController@index')->name('kampusku');
Route::get('profilkampus/{id}', 'frontController@profilkampus')->name('profilkampus');
Route::get('/DaftarSemuaKampus', 'frontController@allkampus')->name('all-kampus');

// Auth::routes(['verify' => true]);
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/siakad', 'HomeController@mhs')->name('mhs');
// dosen
Route::get('/dosen', 'Admin\ProfildosenController@index')->name('dosen');


Route::get('/pmb', 'HomeController@pmb')->name('pmb');
Route::get('/daftarpmb/{id}', 'HomeController@daftarpmb')->name('daftarpmb');
Route::post('/daftarpmb/daftarpmbstore', 'HomeController@daftarpmbstore')->name('daftarpmbstore');
Route::post('/getkabupaten', 'HomeController@getkabupaten')->name('getkabupaten');
Route::post('/getkecamatan', 'HomeController@getkecamatan')->name('getkecamatan');
Route::post('/getdesa', 'HomeController@getdesa')->name('getdesa');

//Camaba
Route::group(['middleware' => ['auth', 'CekRole:camaba']], function () {
    Route::get('formpendaftaran', 'Pmb\pmbController@create')->name('form.daftar');
    Route::post('pendaftaran', 'Pmb\pmbController@store')->name('simpan.daftar');
});

Route::group(['middleware' => ['auth', 'CekRole:admin'], 'prefix' => 'Admin_Kemahasiswaan'], function () {
    Route::namespace('Admin')->group(function () {
        Route::resource('kampus', 'kampusController')->parameters(['kampus' => 'kampus',]);
        Route::resource('prodi', 'prodiController');
        Route::resource('fakultas', 'FakultasController');
        // Route::resource('dataprodikampus', 'prodikampusController');
        Route::resource('infopmb', 'infopmbController');
        Route::resource('pendaftar', 'CamabaController');
        Route::resource('student', 'StudentController');
        Route::resource('dosen', 'DosenController');
        Route::get('diterima/{id}/{key}', 'CamabaController@diterima')->name('diterima');
    });
});

Route::group(['middleware' => ['auth', 'CekRole:mahasiswa'], 'prefix' => 'Mahasiswa'], function () {
    Route::namespace('Mahasiswa')->group(function () {

        /* Route::get('/siswa','SiswaController@index');
        Route::post('/siswa/create','SiswaController@create');
        Route::get('/siswa/{siswa}/edit','SiswaController@edit');
        Route::post('/siswa/{siswa}/update','SiswaController@update');
        Route::get('/siswa/{siswa}/delete','SiswaController@delete');
        Route::get('/siswa/{siswa}/profile','SiswaController@profile');
        Route::post('/siswa/{siswa}/addnilai','SiswaController@addnilai'); */

        // Route::get('/mahasiswa/{mahasiswa}/edit','mahasiswaController@edit');

        // Route::get('/mahasiswa/{mahasiswa}/edit', 'mahasiswaController@edit');
        Route::resource('mahasiswa', 'mahasiswaController');
        // Route::resource('mahasiswa', 'mahasiswaController')->parameters(['mahasiswa' => 'mahasiswa',]);
        Route::get('krs', 'mahasiswaController@krs')->name('krs');
        Route::get('khs', 'mahasiswaController@khs')->name('khs');
        Route::get('transkrip', 'mahasiswaController@nilai')->name('nilai');
        Route::get('Elearning', 'mahasiswaController@learning')->name('learning');
        Route::get('materi', 'mahasiswaController@materi')->name('materi');
    });
});

Route::group(['middleware' => ['auth', 'verified', 'CekRole:pmb'], 'prefix' => 'Pmb'], function () {
    Route::namespace('Pmb')->group(function () {
        Route::resource('pmb', 'pmbController')->parameters(['pmb' => 'pmb',]);
        Route::get('pendaftaran', 'pmbController@pendaftaran')->name('pendaftaran');
    });
});

Route::group(['middleware' => ['auth', 'CekRole:adminakademik'], 'prefix' => 'Adminakademik'], function () {
    Route::namespace('Admin')->group(function () {
        Route::resource('datatahunakademik', 'DatathnakademikController')->parameters(['datatahunakademik' => 'datatahunakademik',]);
        Route::resource('datasemester', 'DatasemesterController');
        Route::resource('datamatakuliah', 'DatamatakuliahController');
        Route::resource('jadwalkuliah', 'JadwalkuliahController');
        Route::resource('datakrs', 'DatakrsController');
        Route::resource('datakhs', 'DatakhsController');
        Route::resource('datatranskipnilai', 'DatatranskipnilaiController');
    });
});

Route::group(['middleware' => ['auth', 'CekRole:admindosen'], 'prefix' => 'Admindosen'], function () {
    Route::namespace('Admin')->group(function () {
        Route::resource('profildosen', 'ProfildosenController')->parameters(['profildosen' => 'profildosen',]);
        Route::resource('jadwaldosen', 'JadwalkuliahdosenController');
        Route::resource('absensi', 'AbsensiController');
        Route::resource('modulmateri', 'ModulmateriController');
        Route::get('/detailmateri/{id}/materi', 'ModulmateriController@materi')->name('detailmateri');
    });
});

app/Fakultas.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Fakultas extends Model
{
    protected $table = 'fakultas';

    protected $fillable = [
        'kampus_id',
        'nama_fakultas',
        'akreditasi_fakultas',
    ];

    public function kampus()
    {
        return $this->hasOne(Kampus::class, 'id', 'kampus_id');
    }

    public function prodi()
    {
        return $this->hasMany(Prodi::class, 'prodi_id', 'id');
    }



    // public function kampus()
    // {
    //     // satu kampus memiliki banyak fakultas
    //     return $this->hasMany(Kampus::class, 'kampus_id', 'id');
    // }
}

app/Http/Controllers/Admin/FakultasController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\FakultasCreate;
use App\Http\Requests\Admin\FakultasUpdate;
use Illuminate\Http\Request;
use App\Fakultas;
use App\Kampus;

class FakultasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $data = Fakultas::paginate(15);
        $data = Fakultas::with('kampus')->paginate(10);
        //dd($data);

        return view('Admin_Kemahasiswaan.Fakultas.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $kampus = Kampus::all();
        // dd($kampus);
        return view('Admin_Kemahasiswaan.Fakultas.create', compact('kampus'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $request->validate([
            'nama_fakultas'        => 'required',
            'akreditasi_fakultas'  => 'required',
        ]);
        $data = $request->all();
        // dd($data);
        Fakultas::create($data);

        toast('Data Fakultas Berhasil Ditambahkan', 'success');
        return redirect()->route('fakultas.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    // public function edit( /* $id  */)
    public function edit($id)
    {
        //
        $kampus = Kampus::get();
        // $kampus = Kampus::find($id)->first();
        $fakultas = Fakultas::find($id);
        // dd($fakultas);
        return view('Admin_Kemahasiswaan.Fakultas.edit', compact('kampus', 'fakultas'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $request->validate([
            'nama_fakultas'        => 'required',
            'akreditasi_fakultas'  => 'required',
        ]);

        $data = $request->all();
        $fakultas = Fakultas::find($id);

        $fakultas->update($data);

        toast('Data Fakultas berhasil Di Update', 'success');
        return redirect()->route('fakultas.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Fakultas::where('id', $id)->delete();

        return redirect()->back();
    }
}

resources/views/Admin_Kemahasiswaan/Fakultas/create.blade.php
@extends('layouts.cork')

@section('content')
    <div id="flStackForm" class="col-lg-12 layout-spacing layout-top-spacing">
        <div class="statbox widget box box-shadow col-md-12">
            <div class="widget-header">
                <div class="row">
                    <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                        <h4>Tambah Data Fakultas</h4>
                    </div>
                </div>
            </div>
            <div class="widget-content widget-content-area">
                <form action="{{ route('fakultas.store') }}" method="POST" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <label>Nama Kampus</label>
                        <select class="form-control  basic" name="kampus_id">
                            <option value="">Pilih kampus</option>
                            @forelse ($kampus as $item)
                                <option value="{{ $item->id }}">{{ $item->nama_kampus }}</option>
                            @empty
                            @endforelse
                        </select>
                    </div>
                    <div class="form-group">
                        <label>Nama Fakultas</label>
                        <input type="text" name="nama_fakultas" class="form-control @error('nama_fakultas') is-invalid @enderror" 
                        placeholder="Masukkan Nama Fakultas" value="{{ old('nama_fakultas') }}">
                        @error('nama_fakultas')
                            <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Akreditasi Fakultas</label>
                        <select class="form-control" name="akreditasi_fakultas">
                            <option value="">Pilih Akreditasi</option>
                            <option value="A">A</option>
                            <option value="B">B</option>
                            <option value="C">C</option>
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary mt-3">Simpan</button>
                </form>
            </div>
        </div>
    </div>
@endsection

@section('js')
    <script>
        CKEDITOR.replace('tahapan');
    </script>
@endsection

resources/views/Admin_Kemahasiswaan/Fakultas/edit.blade.php
@extends('layouts.cork')

@section('content')
<div id="flStackForm" class="col-lg-12 layout-spacing layout-top-spacing">
    <div class="statbox widget box box-shadow col-md-12">
        <div class="widget-header">                                
            <div class="row">
                <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                    <h4>Edit Data Fakultas</h4>
                </div>                                                                        
            </div>
        </div>
        <div class="widget-content widget-content-area">
            <form action="{{ route('fakultas.update', $fakultas->id ) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label>Nama Kampus</label>
                    <select class="form-control basic" name="kampus_id">
                        <option value="">Pilih kampus</option>
                        @forelse ($kampus as $item)
                            <option {{ $fakultas->kampus_id == $item->id ? 'selected' : '' }}
                                value="{{ $item->id }}">{{ $item->nama_kampus }}</option>
                        @empty
                        @endforelse
                    </select>
                </div>
                <div class="form-group">
                    <label>Nama Fakultas</label>
                    <input type="text" name="nama_fakultas" class="form-control" placeholder="Masukkan Nama"
                        value="{{ $fakultas->nama_fakultas ?? old('nama_fakultas') }}">
                </div>
                <div class="form-group">
                    <label>Akreditasi Fakultas</label>
                    <select name="akreditasi_fakultas" class="form-control">
                        <option value="A" @if($fakultas->akreditasi_fakultas == 'A') selected @endif>A</option>
                        <option value="B" @if($fakultas->akreditasi_fakultas == 'B') selected @endif>B</option>
                        <option value="C" @if($fakultas->akreditasi_fakultas == 'C') selected @endif>C</option>
                    </select>
                </div>
                <button type="submit" class="btn btn-primary mt-3">Update</button>
            </form>
        </div>
    </div>
</div>
@endsection

@section('js')

<script>
    var ss = $(".basic").select2({
        tags: true,
    });
</script>


<script>
    CKEDITOR.replace( 'editor1' );
</script>
@endsection

resources/views/Admin_Kemahasiswaan/Fakultas/index.blade.php
@extends('layouts.cork')

@section('content')
    <div id="tableHover" class="col-lg-12 col-12 layout-spacing">
        <div class="statbox widget box box-shadow">
            <div class="widget-header">
                <div class="row">
                    <div class="col-xl-6 col-md-6 col-sm-6 col-12">
                        <h4>DATA FAKULTAS</h4>
                    </div>
                    <div class="col-xl-6 col-md-6 col-sm-6 col-12 text-right">
                        <a class="btn btn-outline-primary mt-3 mr-3" href="{{ route('fakultas.create') }}">Tambah</a>
                    </div>
                </div>
            </div>
            <div class="widget-content widget-content-area">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover mb-4">
                        <thead>
                            <tr>
                                <th class="text-center">No</th>
                                <th class="text-center">Nama Kampus</th>
                                <th class="text-center">Nama Fakultas</th>
                                <th class="text-center">Akreditasi Fakultas</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($data as $item => $fakultas )
                                <tr>
                                    <td align="center">{{ $data->firstItem() + $item }} </td>
                                    <td align="center">{{ $fakultas->kampus['nama_kampus'] }} </td>
                                    <td align="center">{{ $fakultas->nama_fakultas }} </td>
                                    <td align="center">{{ $fakultas->akreditasi_fakultas }} </td>
                                    <td class="text-center">
                                        <a href="{{ route('fakultas.edit', $fakultas) }}">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                                viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
                                                stroke-linecap="round" stroke-linejoin="round"
                                                class="feather feather-edit-2">
                                                <path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path>
                                            </svg>
                                        </a>
                                        <form action="{{ route('fakultas.destroy', $fakultas) }}" method="POST"
                                            onsubmit="return confirm('Hapus Data, Anda Yakin ?')">
                                            {!! method_field('delete') . csrf_field() !!}
                                            <button class="dropdown-item" type="submit">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                                    viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
                                                    stroke-linecap="round" stroke-linejoin="round"
                                                    class="feather feather-trash-2 icon">
                                                    <polyline points="3 6 5 6 21 6"></polyline>
                                                    <path
                                                        d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2">
                                                    </path>
                                                </svg>
                                            </button>
                                        </form>
                                
                                    </td>
                                </tr>
                            @empty
                            @endforelse
                        </tbody>
                    </table>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    {{ $data->links() }}  
                </div>
            </div>
        </div>
    </div>
@endsection