routes/web.php
<?php

// use App\Http\Controllers\IndoregionController
use App\Http\Controllers\Mahasiswa\mahasiswaController;
use App\Kampus;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|   // $kampus = Kampus::paginate(8);
*/

Route::get('/', 'frontController@index')->name('kampusku');
Route::get('profilkampus/{id}', 'frontController@profilkampus')->name('profilkampus');
Route::get('/DaftarSemuaKampus', 'frontController@allkampus')->name('all-kampus');

// Auth::routes(['verify' => true]);
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/siakad', 'HomeController@mhs')->name('mhs');
// dosen
Route::get('/dosen', 'Admin\ProfildosenController@index')->name('dosen');


Route::get('/pmb', 'HomeController@pmb')->name('pmb');
Route::get('/daftarpmb/{id}', 'HomeController@daftarpmb')->name('daftarpmb');
Route::post('/daftarpmb/daftarpmbstore', 'HomeController@daftarpmbstore')->name('daftarpmbstore');
Route::post('/getkabupaten', 'HomeController@getkabupaten')->name('getkabupaten');
Route::post('/getkecamatan', 'HomeController@getkecamatan')->name('getkecamatan');
Route::post('/getdesa', 'HomeController@getdesa')->name('getdesa');

//Camaba
Route::group(['middleware' => ['auth', 'CekRole:camaba']], function () {
    Route::get('formpendaftaran', 'Pmb\pmbController@create')->name('form.daftar');
    Route::post('pendaftaran', 'Pmb\pmbController@store')->name('simpan.daftar');
});

Route::group(['middleware' => ['auth', 'CekRole:admin'], 'prefix' => 'Admin_Kemahasiswaan'], function () {
    Route::namespace('Admin')->group(function () {
        Route::resource('kampus', 'kampusController')->parameters(['kampus' => 'kampus',]);
        Route::resource('prodi', 'prodiController');
        Route::resource('fakultas', 'FakultasController');
        // Route::resource('dataprodikampus', 'prodikampusController');
        Route::resource('infopmb', 'infopmbController');
        Route::resource('pendaftar', 'CamabaController');
        Route::resource('student', 'StudentController');
        Route::resource('dosen', 'DosenController');
        Route::get('diterima/{id}/{key}', 'CamabaController@diterima')->name('diterima');
    });
});

Route::group(['middleware' => ['auth', 'CekRole:mahasiswa'], 'prefix' => 'Mahasiswa'], function () {
    Route::namespace('Mahasiswa')->group(function () {

        /* Route::get('/siswa','SiswaController@index');
        Route::post('/siswa/create','SiswaController@create');
        Route::get('/siswa/{siswa}/edit','SiswaController@edit');
        Route::post('/siswa/{siswa}/update','SiswaController@update');
        Route::get('/siswa/{siswa}/delete','SiswaController@delete');
        Route::get('/siswa/{siswa}/profile','SiswaController@profile');
        Route::post('/siswa/{siswa}/addnilai','SiswaController@addnilai'); */

        // Route::get('/mahasiswa/{mahasiswa}/edit','mahasiswaController@edit');

        // Route::get('/mahasiswa/{mahasiswa}/edit', 'mahasiswaController@edit');
        Route::resource('mahasiswa', 'mahasiswaController');
        // Route::resource('mahasiswa', 'mahasiswaController')->parameters(['mahasiswa' => 'mahasiswa',]);
        Route::get('krs', 'mahasiswaController@krs')->name('krs');
        Route::get('khs', 'mahasiswaController@khs')->name('khs');
        Route::get('transkrip', 'mahasiswaController@nilai')->name('nilai');
        Route::get('Elearning', 'mahasiswaController@learning')->name('learning');
        Route::get('materi', 'mahasiswaController@materi')->name('materi');
    });
});

Route::group(['middleware' => ['auth', 'verified', 'CekRole:pmb'], 'prefix' => 'Pmb'], function () {
    Route::namespace('Pmb')->group(function () {
        Route::resource('pmb', 'pmbController')->parameters(['pmb' => 'pmb',]);
        Route::get('pendaftaran', 'pmbController@pendaftaran')->name('pendaftaran');
    });
});

Route::group(['middleware' => ['auth', 'CekRole:adminakademik'], 'prefix' => 'Adminakademik'], function () {
    Route::namespace('Admin')->group(function () {
        Route::resource('datatahunakademik', 'DatathnakademikController')->parameters(['datatahunakademik' => 'datatahunakademik',]);
        Route::resource('datasemester', 'DatasemesterController');
        Route::resource('datamatakuliah', 'DatamatakuliahController');
        Route::resource('jadwalkuliah', 'JadwalkuliahController');
        Route::resource('datakrs', 'DatakrsController');
        Route::resource('datakhs', 'DatakhsController');
        Route::resource('datatranskipnilai', 'DatatranskipnilaiController');
    });
});

Route::group(['middleware' => ['auth', 'CekRole:admindosen'], 'prefix' => 'Admindosen'], function () {
    Route::namespace('Admin')->group(function () {
        Route::resource('profildosen', 'ProfildosenController')->parameters(['profildosen' => 'profildosen',]);
        Route::resource('jadwaldosen', 'JadwalkuliahdosenController');
        Route::resource('absensi', 'AbsensiController');
        Route::resource('modulmateri', 'ModulmateriController');
        Route::get('/detailmateri/{id}/materi', 'ModulmateriController@materi')->name('detailmateri');
    });
});

app/Infopmb.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Infopmb extends Model
{
    protected $table = 'info_pmbs';

    protected $guarded = [];

    public function kampus()
    {
        return $this->hasOne(Kampus::class, 'id', 'kampus_id');
    }
}

app/Http/Controllers/Admin/infopmbController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Infopmb;
use App\Kampus;
use Illuminate\Http\Request;
use Symfony\Polyfill\Intl\Idn\Info;

class infopmbController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Infopmb::with('kampus')->paginate(10);

        return view('Admin_Kemahasiswaan.Infopmb.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $kampus   = Kampus::all();

        return view('Admin_Kemahasiswaan.Infopmb.create', compact('kampus'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'judul_info'        => 'required',
            'tahapanseleksi'    => 'required',
            'waktupendaftaran_start'  => 'required',
            'waktupendaftaran_end'  => 'required',
            'biayapendaftaran'  => 'required',
        ]);

        $data_array = [
            'seleksi_1' => $request->tahapanseleksi,
            'seleksi_2' => $request->tahapanseleksi_2,
            'seleksi_3' => $request->tahapanseleksi_3,
            'seleksi_4' => $request->tahapanseleksi_4,
            'seleksi_5' => $request->tahapanseleksi_5,
            'seleksi_6' => $request->tahapanseleksi_6,
            'seleksi_7' => $request->tahapanseleksi_7,
            'seleksi_8' => $request->tahapanseleksi_8,
        ];

        // $data = $request->all();

        $data['kampus_id'] = $request->kampus_id;
        $data['judul_info'] = $request->judul_info;
        $data['waktupendaftaran_start'] = $request->waktupendaftaran_start;
        $data['waktupendaftaran_end'] = $request->waktupendaftaran_end;
        $data['biayapendaftaran'] = $request->biayapendaftaran;
        $data['tahun_akademik'] = $request->tahun_akademik;
        $data['tahapanseleksi'] = json_encode($data_array);

        if ($request->has('fotoposter')) {
            $foto           = $request->fotoposter;
            $new_foto       = time() . 'infoPMB' . $foto->getClientOriginalName();
            $tujuan_uploud  = 'uplouds/InfoPMB/';
            $foto->move($tujuan_uploud, $new_foto);
            $data['fotoposter']   = $tujuan_uploud . $new_foto;
        }

        // dd($data);

        Infopmb::create($data);

        toast('Data Berhasil Ditambahkan', 'success');
        return redirect()->route('infopmb.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $kampus = Kampus::get();

        $infopmb = Infopmb::find($id);

        $json = json_decode($infopmb->tahapanseleksi, true);

        return view('Admin_Kemahasiswaan.Infopmb.edit', compact('infopmb', 'kampus', 'json'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'judul_info'        => 'required',
            'tahapanseleksi'    => 'required',
            'waktupendaftaran_start'  => 'required',
            'waktupendaftaran_end'  => 'required',
            'biayapendaftaran'  => 'required',
        ]);

        $data_array = [
            'seleksi_1' => $request->tahapanseleksi,
            'seleksi_2' => $request->tahapanseleksi_2,
            'seleksi_3' => $request->tahapanseleksi_3,
            'seleksi_4' => $request->tahapanseleksi_4,
            'seleksi_5' => $request->tahapanseleksi_5,
            'seleksi_6' => $request->tahapanseleksi_6,
            'seleksi_7' => $request->tahapanseleksi_7,
            'seleksi_8' => $request->tahapanseleksi_8,
        ];

        $info = Infopmb::findorfail($id);

        if ($request->has('fotoposter')) {

            //upload new image
            $foto = $request->fotoposter;
            $new_foto = time() . 'infoPMB' . $foto->getClientOriginalName();
            $tujuan_uploud = 'uplouds/InfoPMB/';
            $foto->move($tujuan_uploud, $new_foto);

            //delete old image in local
            if (file_exists(($info->logo))) {
                unlink(($info->logo));
            }

            //update with new image
            $info->update([
                'fotoposter'              => $tujuan_uploud . $new_foto,
                'kampus_id'               => $request->kampus_id,
                'judul_info'              => $request->judul_info,
                'waktupendaftaran_start'  => $request->waktupendaftaran_start,
                'waktupendaftaran_end'    => $request->waktupendaftaran_end,
                'biayapendaftaran'        => $request->biayapendaftaran,
                'tahun_akademik'          => $request->tahun_akademik,
                'tahapanseleksi'          => json_encode($data_array),
            ]);
        } else {
            //update without image
            $info->update([
                'kampus_id'               => $request->kampus_id,
                'judul_info'              => $request->judul_info,
                'waktupendaftaran_start'  => $request->waktupendaftaran_start,
                'waktupendaftaran_end'    => $request->waktupendaftaran_end,
                'biayapendaftaran'        => $request->biayapendaftaran,
                'tahun_akademik'          => $request->tahun_akademik,
                'tahapanseleksi'          => json_encode($data_array),
            ]);
        }

        toast('Data Info PMB Berhasil Di Update', 'success');
        return redirect()->route('infopmb.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        Infopmb::where('id', $id)->delete();

        return redirect()->back();
    }
}

resources/views/Admin_Kemahasiswaan/Infopmb/create.blade.php
@extends('layouts.cork')

@section('content')
    <div id="flStackForm" class="col-lg-12 layout-spacing layout-top-spacing">
        <div class="statbox widget box box-shadow col-md-12">
            <div class="widget-header">
                <div class="row">
                    <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                        <h4>Tambah Data Kampus</h4>
                    </div>
                </div>
            </div>
            <div class="widget-content widget-content-area">
                <form action="{{ route('infopmb.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                        <label>Pilih Kampus</label>
                        <select class="form-control basic" name="kampus_id" required>
                            <option value="">Pilih Kampus</option>
                            @foreach ($kampus as $item)
                                <option value="{{ $item->id }}">{{ $item->nama_kampus }} </option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label>Judul Info PMB</label>
                        <input type="text" name="judul_info"
                            class="form-control @error('judul_info') is-invalid @enderror" placeholder="Judul Info PMB"
                            value="{{ old('judul_info') }}">
                        @error('judul_info')
                            <div class="invalid-feedback">{{ $message }} </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Waktu Pendaftaran</label>
                        <div class="row">
                            <div class="col-md-3 mb-3">
                                <input type="date" name="waktupendaftaran_start"
                                    class="form-control @error('waktupendaftaran_start') is-invalid @enderror"
                                    placeholder="" value="{{ old('waktupendaftaran_start') }}">
                                @error('waktupendaftaran_start')
                                    <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="col-md-1 mb-3 mt-2 text-center">
                                <span><b>sampai</b></span>
                            </div>
                            <div class="col-md-3 mb-3">
                                <input type="date" name="waktupendaftaran_end"
                                    class="form-control @error('waktupendaftaran_end') is-invalid @enderror" placeholder=""
                                    value="{{ old('waktupendaftaran_end') }}">
                                @error('waktupendaftaran_end')
                                    <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Biaya Pendaftaran</label>
                        <input type="number" name="biayapendaftaran"
                            class="form-control @error('biayapendaftaran') is-invalid @enderror"
                            placeholder="Masukkan Biaya Pendaftaran" value="{{ old('biayapendaftaran') }}">
                        @error('biayapendaftaran')
                            <div class="invalid-feedback">{{ $message }} </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Tahun Akademik</label>
                        <input type="text" name="tahun_akademik"
                            class="form-control @error('tahun_akademik') is-invalid @enderror"
                            placeholder="Masukkan Tahun Akademik" value="{{ old('tahun_akademik') }}">
                        @error('tahun_akademik')
                            <div class="invalid-feedback">{{ $message }} </div>
                        @enderror
                    </div>
                    <div class="form-group mb-4">
                        <label for="exampleFormControlTextarea1">Tahapan Seleksi</label>
                        <div class="row">
                            <div class="col-md-3 mb-3">
                                <input type="text" name="tahapanseleksi"
                                    class="form-control @error('tahapanseleksi') is-invalid @enderror"
                                    placeholder="Tahapan 1" value="{{ old('tahapanseleksi') }}">
                            </div>
                            <div class="col-md-3 mb-3">
                                <input type="text" name="tahapanseleksi_2"
                                    class="form-control @error('tahapanseleksi') is-invalid @enderror"
                                    placeholder="Tahapan 2" value="{{ old('tahapanseleksi') }}">
                            </div>
                            <div class="col-md-3 mb-3">
                                <input type="text" name="tahapanseleksi_3"
                                    class="form-control @error('tahapanseleksi') is-invalid @enderror"
                                    placeholder="Tahapan 3" value="{{ old('tahapanseleksi') }}">
                            </div>
                            <div class="col-md-3 mb-3">
                                <input type="text" name="tahapanseleksi_4"
                                    class="form-control @error('tahapanseleksi') is-invalid @enderror"
                                    placeholder="Tahapan 4" value="{{ old('tahapanseleksi') }}">
                            </div>
                            <div class="col-md-3 mb-3">
                                <input type="text" name="tahapanseleksi_5"
                                    class="form-control @error('tahapanseleksi') is-invalid @enderror"
                                    placeholder="Tahapan 5" value="{{ old('tahapanseleksi') }}">
                            </div>
                            <div class="col-md-3 mb-3">
                                <input type="text" name="tahapanseleksi_6"
                                    class="form-control @error('tahapanseleksi') is-invalid @enderror"
                                    placeholder="Tahapan 6" value="{{ old('tahapanseleksi') }}">
                            </div>
                            <div class="col-md-3 mb-3">
                                <input type="text" name="tahapanseleksi_7"
                                    class="form-control @error('tahapanseleksi') is-invalid @enderror"
                                    placeholder="Tahapan 7" value="{{ old('tahapanseleksi') }}">
                            </div>
                            <div class="col-md-3 mb-3">
                                <input type="text" name="tahapanseleksi_8"
                                    class="form-control @error('tahapanseleksi') is-invalid @enderror"
                                    placeholder="Tahapan 8" value="{{ old('tahapanseleksi') }}">
                            </div>
                        </div>
                    </div>
                    <div class="form-group mb-4 mt-3">
                        <label for="exampleFormControlFile1">Foto Poster</label>
                        <input type="file" name="fotoposter" class="form-control-file" id="exampleFormControlFile1">
                    </div>
                    <button type="submit" class="btn btn-primary mt-3">Simpan</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/Admin_Kemahasiswaan/Infopmb/index.blade.php
@extends('layouts.cork')

@section('content')
    <div id="tableHover" class="col-lg-12 col-12 layout-spacing">
        <div class="statbox widget box box-shadow">
            <div class="widget-header">
                <div class="row">
                    <div class="col-xl-6 col-md-6 col-sm-6 col-12">
                        <h4>DATA INFO PMB</h4>
                    </div>
                    <div class="col-xl-6 col-md-6 col-sm-6 col-12 text-right">
                        <a class="btn btn-outline-primary mt-3 mr-3" href="{{ route('infopmb.create') }}">Tambah</a>
                    </div>
                </div>
            </div>
            <div class="widget-content widget-content-area">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover mb-4">
                        <thead>
                            <tr>
                                <th class="text-center">No</th>
                                <th class="text-center">Nama Kampus</th>
                                <th class="text-center">Judul Info</th>
                                <th class="text-center">Tahapan Seleksi</th>
                                <th class="text-center">Waktu Pendaftaran</th>
                                <th class="text-center">Foto Poster </th>
                                <th class="text-center">Biaya Pendaftaran</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($data as $item => $infopmb)
                                @php
                                    $json = json_decode($infopmb->tahapanseleksi, true);
                                @endphp
                                <tr class="text-center">
                                    <td> {{ $data->firstItem() + $item }}</td>
                                    <td> {{ $infopmb->kampus['nama_kampus'] }}</td>
                                    <td> {{ $infopmb->judul_info }}</td>
                                    <td class="text-left">
                                        <p>Tahap 1 : {{ $json['seleksi_1'] }}</p>
                                        <p>Tahap 2 : {{ $json['seleksi_2'] }}</p>
                                        <p>Tahap 3 : {{ $json['seleksi_3'] }}</p>
                                        <p>Tahap 4 : {{ $json['seleksi_4'] }}</p>
                                        <p>Tahap 5 : {{ $json['seleksi_5'] }}</p>
                                        <p>Tahap 6 : {{ $json['seleksi_6'] }}</p>
                                        <p>Tahap 7 : {{ $json['seleksi_7'] }}</p>
                                        <p>Tahap 8 : {{ $json['seleksi_8'] }}</p>
                                    </td>
                                    <td> {{ Carbon\Carbon::parse($infopmb->waktupendaftaran_start)->translatedFormat('d F Y') }}
                                        -
                                        {{ Carbon\Carbon::parse($infopmb->waktupendaftaran_end)->translatedFormat('d F Y') }}
                                    </td>
                                    <td>
                                        <img width="100px" src="{{ asset($infopmb->fotoposter) }}" alt="">
                                    </td>
                                    <td>Rp. {{ number_format($infopmb->biayapendaftaran) }}</td>
                                    <td class="text-center">
                                        <a href="{{ route('infopmb.edit', $infopmb) }}">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                                viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
                                                stroke-linecap="round" stroke-linejoin="round"
                                                class="feather feather-edit-2">
                                                <path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path>
                                            </svg>
                                        </a>
                                        <form action="{{ route('infopmb.destroy', $infopmb) }}" method="POST"
                                            onsubmit="return confirm('Hapus Data, Anda Yakin ?')">
                                            {!! method_field('delete') . csrf_field() !!}
                                            <button class="dropdown-item" type="submit">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                                    viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                                    stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                                                    class="feather feather-trash-2 icon">
                                                    <polyline points="3 6 5 6 21 6"></polyline>
                                                    <path
                                                        d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2">
                                                    </path>
                                                </svg>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @empty
                            @endforelse
                        </tbody>
                    </table>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    {{ $data->links() }}
                </div>
            </div>
        </div>
    </div>
@endsection